### PR TITLE
Jsy8869 - 6회차 문제풀이

### PR DESCRIPTION
**Pull request by JSY8869**
[](https://github.com/JSY8869)@JSY8869
[Add files via upload](https://github.com/JSY8869/CodingTestStudy/pull/24/commits/9b25330cc932f5139ce7e26aeffb4a528d7cd369)

@JSY8869
[Revert "Add files via upload"](https://github.com/JSY8869/CodingTestStudy/pull/24/commits/69644dc7ff1d3587fd8f7eadbaed2d945110bb17)

는 github desktop 고장나서 뻘짓한거....

### CODE REVIEW

**Review by CokeLee777 — COMMENTED** [review]
Network Delay time - Good! , 큐 돌릴때 기능만 함수로 빼서 놓는게 좋을듯

**Review by CokeLee777 — COMMENTED** [review]
Broken Calculator - Good!

**Review by CokeLee777 — COMMENTED** [review]
Spiral Matrix - 파이썬은 그래프 돌리는 라이브러리도있냐..

**Review by CokeLee777 — COMMENTED** [review]
Open the Lock - 완성도 높은 코드 Good!

**Comment by dongdaang** [comment]
networkDelayTime - Good!!

**Comment by dongdaang** [comment]
brokenCalc - 깔끔 그 자체...

**Comment by dongdaang** [comment]
spiralOrder - ㄷㄷ..

**Comment by dongdaang** [comment]
Open the Lock - 깔끔하네요 good good!

**Pull request merged**
